# Generated by Django 4.2.13 on 2024-05-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=4, verbose_name='Activation Token'),
        ),
    ]
