# Generated by Django 4.2.7 on 2024-05-31 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0002_customuser_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500, verbose_name='User Biography')),
                ('port_link', models.URLField(verbose_name='Porfolio Link')),
                ('country', models.TextField(max_length=200, verbose_name='Country')),
                ('language', models.TextField(max_length=200, verbose_name='Language')),
                ('professional_role', models.TextField(max_length=200, verbose_name='Professional Role')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('skills', models.TextField(max_length=500, verbose_name='Skills')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_information', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
