# Generated by Django 4.2.7 on 2024-06-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapp', '0003_personalinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='auth_token',
            new_name='activation_token',
        ),
    ]
